### ISSUE TITLE
Domain option is broken

### ISSUE THREAD

**Issue by AYIV** [TechnikEmpire/DistillNET#11]
Hi!

Thanks a lot for your work, and sorry for my english ha-ha :D
I've started to use your library and found a lot of mismatched rules that confused me from the beginning.

Than I found your last commit where domain option parsing was, as I understand, reformatted with one simple mistake.
You can find my comment to that commit, please fix it when you'll have a minute!

Thanks.

**Comment by TechnikEmpire** [comment]
@AYIV I use this library in production code so I need more details here about what exactly you think the issue is please. Can you give me an example of a rule that is not being parsed properly? Thanks.

**Comment by TechnikEmpire** [comment]
@AYIV Actually I don't use 1.4, I think I see what you're talking about now. Thanks. I'm going to hide the 1.4 release off of nuget and push a 1.5 version as soon as I can.

**Comment by AYIV** [comment]
Hi! I'm using 1.3.1 version.

Maybe I'm doing smth wrong, but:

AbpFormatRuleParser.cs, line 264
`if(allOptions[i].Length > 7 && allOptions[i][0] == 'd' && allOptions[i][7] == '=')`
this line - should be allOptions[i][6] (and it was, you can check it in commit history), cause "domain" has 6 letters, than offset for the "=" will be 6

AbpFormatRuleParser.cs, line 286
'domainsOption = domainsOption.Substring(8);'
should be 7 instead of 8, because of "domain="

**Comment by TechnikEmpire** [comment]
@AYIV Confirmed, my bad. We're not even using the `$domain` option in production so of course I missed this. I think I got it in my mind that the option was named `$domains`. Anyway thanks for the report. I'm tackling this now. Also, I'm rolling back the use of hashsets and stuff. We lost a ton of speed in 1.4 and I thought it was because I moved to .NET standard and Microsoft's sqlite library. However, it turns out that the use of the hashsets murdered performance.
